# Tests for Exercise 01
# Written by your teacher. Do not edit this file.
# Run: pytest

from solution_completed import * 

# =============================================================================
# Task 1 — Basic Functions
# =============================================================================
 
def test_greet_normal():
    assert greet("Alice") == "Hello, Alice!"
 
def test_greet_another_name():
    assert greet("Wei Jing") == "Hello, Wei Jing!"
 
def test_greet_empty_string():
    assert greet("") == "Hello, !"
 
# ---
 
def test_add_positive_numbers():
    assert add(2, 3) == 5
 
def test_add_negative_numbers():
    assert add(-4, -6) == -10
 
def test_add_mixed_signs():
    assert add(-3, 7) == 4
 
def test_add_zeros():
    assert add(0, 0) == 0
 
# ---
 
def test_is_even_even_number():
    assert is_even(4) == True
 
def test_is_even_odd_number():
    assert is_even(7) == False
 
def test_is_even_zero():
    assert is_even(0) == True
 
def test_is_even_negative_even():
    assert is_even(-2) == True
 
def test_is_even_negative_odd():
    assert is_even(-3) == False
 
# ---
 
def test_circle_area_radius_1():
    assert circle_area(1) == 3.14
 
def test_circle_area_radius_5():
    assert circle_area(5) == 78.54
 
def test_circle_area_radius_0():
    assert circle_area(0) == 0.0
 
def test_circle_area_radius_10():
    assert circle_area(10) == 314.16
 
# =============================================================================
# Task 2 — Unary Functions
# =============================================================================
 
def test_double_positive():
    assert double(3) == 6
 
def test_double_zero():
    assert double(0) == 0
 
def test_double_negative():
    assert double(-4) == -8
 
# ---
 
def test_square_positive():
    assert square(4) == 16
 
def test_square_zero():
    assert square(0) == 0
 
def test_square_negative():
    assert square(-3) == 9
 
# ---
 
def test_negate_positive():
    assert negate(5) == -5
 
def test_negate_negative():
    assert negate(-1) == 1
 
def test_negate_zero():
    assert negate(0) == 0
 
# ---
 
def test_increment_positive():
    assert increment(9) == 10
 
def test_increment_negative():
    assert increment(-1) == 0
 
def test_increment_zero():
    assert increment(0) == 1
 
# ---
 
def test_decrement_positive():
    assert decrement(5) == 4
 
def test_decrement_zero():
    assert decrement(0) == -1
 
def test_decrement_negative():
    assert decrement(-3) == -4
 
# =============================================================================
# Task 3 — Composed Functions
# =============================================================================
 
def test_double_then_square():
    assert double_then_square(3) == 36   # (3*2)² = 36
 
def test_double_then_square_zero():
    assert double_then_square(0) == 0
 
def test_double_then_square_negative():
    assert double_then_square(-2) == 16  # (-2*2)² = 16
 
# ---
 
def test_square_then_double():
    assert square_then_double(3) == 18   # (3²)*2 = 18
 
def test_square_then_double_zero():
    assert square_then_double(0) == 0
 
def test_square_then_double_negative():
    assert square_then_double(-3) == 18  # ((-3)²)*2 = 18
 
# ---
 
def test_negate_then_square_positive():
    assert negate_then_square(4) == 16   # (-4)² = 16
 
def test_negate_then_square_negative():
    assert negate_then_square(-4) == 16  # (4)² = 16
 
def test_negate_then_square_always_positive():
    # Squaring always produces a positive result
    assert negate_then_square(7) >= 0
    assert negate_then_square(-7) >= 0
 
# ---
 
def test_increment_then_double():
    assert increment_then_double(4) == 10  # (4+1)*2 = 10
 
def test_increment_then_double_zero():
    assert increment_then_double(0) == 2   # (0+1)*2 = 2
 
def test_increment_then_double_negative():
    assert increment_then_double(-3) == -4 # (-3+1)*2 = -4
 
# ---
 
def test_double_then_negate():
    assert double_then_negate(5) == -10  # -(5*2) = -10
 
def test_double_then_negate_negative():
    assert double_then_negate(-3) == 6   # -(-3*2) = 6
 
def test_double_then_negate_zero():
    assert double_then_negate(0) == 0
 
# ---
 
def test_double_square_negate():
    assert double_square_negate(3) == -36  # -((3*2)²) = -36
 
def test_double_square_negate_negative():
    assert double_square_negate(-3) == -36 # -((-3*2)²) = -36
 
def test_double_square_negate_zero():
    assert double_square_negate(0) == 0
 
# ---
 
def test_inc_inc_double():
    assert inc_inc_double(3) == 10   # (3+1+1)*2 = 10
 
def test_inc_inc_double_zero():
    assert inc_inc_double(0) == 4    # (0+1+1)*2 = 4
 
def test_inc_inc_double_negative():
    assert inc_inc_double(-3) == -2  # (-3+1+1)*2 = -2
