# Tests for Exercise 01
# Written by your teacher. Do not edit this file.
# Run: pytest

from solution import greet, add, is_even, circle_area, describe

# --- Your teacher will fill in the test cases below ---
